// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace SpecFlowCompareSet.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Table comparison mismatch errors")]
    public partial class TableComparisonMismatchErrorsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Expected mismatch errors.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Table comparison mismatch errors", "In order to avoid writing my own collection comparison code\r\nAs a SpecFlow user\r\n" +
                    "I want to compare collections using different criteria", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Match was not expected")]
        public virtual void MatchWasNotExpected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Match was not expected", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Artist",
                        "Album"});
            table1.AddRow(new string[] {
                        "Beatles",
                        "Rubber Soul"});
            table1.AddRow(new string[] {
                        "Pink Floyd",
                        "Animals"});
            table1.AddRow(new string[] {
                        "Muse",
                        "Absolution"});
#line 7
 testRunner.When("I have a collection", ((string)(null)), table1);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Artist",
                        "Album"});
            table2.AddRow(new string[] {
                        "Beatles",
                        "Rubber Soul"});
            table2.AddRow(new string[] {
                        "Pink Floyd",
                        "Animals"});
            table2.AddRow(new string[] {
                        "Muse",
                        "Absolution"});
#line 12
 testRunner.Then("it should not match", ((string)(null)), table2);
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Exact match was not expected")]
        public virtual void ExactMatchWasNotExpected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Exact match was not expected", ((string[])(null)));
#line 18
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Artist",
                        "Album"});
            table3.AddRow(new string[] {
                        "Beatles",
                        "Rubber Soul"});
            table3.AddRow(new string[] {
                        "Pink Floyd",
                        "Animals"});
            table3.AddRow(new string[] {
                        "Muse",
                        "Absolution"});
#line 19
 testRunner.When("I have a collection", ((string)(null)), table3);
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Artist",
                        "Album"});
            table4.AddRow(new string[] {
                        "Beatles",
                        "Rubber Soul"});
            table4.AddRow(new string[] {
                        "Pink Floyd",
                        "Animals"});
            table4.AddRow(new string[] {
                        "Muse",
                        "Absolution"});
#line 24
 testRunner.Then("it should not exactly match", ((string)(null)), table4);
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Not all contained items were expected")]
        public virtual void NotAllContainedItemsWereExpected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Not all contained items were expected", ((string[])(null)));
#line 30
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Artist",
                        "Album"});
            table5.AddRow(new string[] {
                        "Beatles",
                        "Rubber Soul"});
            table5.AddRow(new string[] {
                        "Pink Floyd",
                        "Animals"});
            table5.AddRow(new string[] {
                        "Muse",
                        "Absolution"});
#line 31
 testRunner.When("I have a collection", ((string)(null)), table5);
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Artist",
                        "Album"});
            table6.AddRow(new string[] {
                        "Beatles",
                        "Rubber Soul"});
            table6.AddRow(new string[] {
                        "Muse",
                        "Absolution"});
#line 36
 testRunner.Then("it should not contain all items", ((string)(null)), table6);
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Common items were not expected")]
        public virtual void CommonItemsWereNotExpected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Common items were not expected", ((string[])(null)));
#line 41
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Artist",
                        "Album"});
            table7.AddRow(new string[] {
                        "Beatles",
                        "Rubber Soul"});
            table7.AddRow(new string[] {
                        "Pink Floyd",
                        "Animals"});
            table7.AddRow(new string[] {
                        "Muse",
                        "Absolution"});
#line 42
 testRunner.When("I have a collection", ((string)(null)), table7);
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Artist",
                        "Album"});
            table8.AddRow(new string[] {
                        "Beatles",
                        "Rubber Soul"});
#line 47
 testRunner.Then("it should not contain any of items", ((string)(null)), table8);
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
